-- Creamos la base de datos
DROP DATABASE IF EXISTS blog;
CREATE DATABASE blog DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci;
CREATE USER IF NOT EXISTS blog@localhost IDENTIFIED BY 'blog2022';
GRANT ALL ON blog.* TO 'blog'@'localhost';

use blog;
-- Creamos las tablas
CREATE TABLE articulos (
	id INT NOT NULL AUTO_INCREMENT,
	titulo VARCHAR(120) NOT NULL,
	fecha DATETIME NOT NULL,
	contenido VARCHAR(1024) NOT NULL,
	PRIMARY KEY(id)
) ENGINE = INNODB;

INSERT INTO articulos VALUES
(NULL,'Sanidad recomienda no celebrar las manifestaciones del 8 de marzo: “No ha lugar”','2021-02-24 21:29:59','El Ministerio de Sanidad ha recomendado este miércoles que no se celebren las manifestaciones del 8-M ante la situación epidemiológica, pese a que España ha salido de la situación de riesgo extremo. La ministra Carolina Darias ha asegurado, tras el Consejo Interterritorial de Salud, que “no ha lugar” a celebrar las marchas por el Día Internacional de la Mujer. Darias ha hecho estas declaraciones horas después de que el delegado del Gobierno en Madrid, José Manuel Franco, anunciara que prohibirá todas las convocatorias para esa fecha en la capital (que sigue en riesgo extremo junto con el País Vasco) que tengan una previsión superior a 500 asistentes.'),
(NULL,'La lentitud en las campañas de vacunación obliga a Europa a mantener las restricciones','2021-02-24 19:00:54','La segunda cumbre de la Unión Europea sobre la pandemia de covid-19 desde comienzos de año se saldará este jueves con una prolongación de las restricciones a todos los viajes considerados no esenciales, tanto desde un país comunitario a otro como los procedentes de un país tercero. El lento ritmo de vacunación y el temor a las nuevas variantes del virus obliga a los 27 socios de la Unión a restringir los viajes trasnfronterizos, y está multiplicando los roces por la desconfianza entre unos y otros.'),
(NULL,'Atalanta - Real Madrid en directo, la Champions League en vivo','2021-02-24 20:25:02','Los octavos de final de la Champions no han empezado nada bien para los equipos españoles. Tanto el Barcelona como el Sevilla y el Atlético perdieron en sus duelos de ida en su casa, complicándose el pase a la siguiente ronda.'),
(NULL,'Sánchez anuncia 11.000 millones para hostelería y turismo sin detallar el calendario','2021-02-24 20:17:43','El presidente del Gobierno, Pedro Sánchez, ha anunciado este miércoles en el Congreso un paquete de 11.000 millones de euros para “empresas, pymes y trabajadores autónomos” centradas en los sectores del “turismo, la hostelería y la restauración”. “No queremos solamente salvar empresas, sino reforzarlas”, ha dicho Sánchez. El anuncio se produce en pleno debate sobre la necesidad de que el Estado destine ayudas directas a salvar empresas, sobre todo pequeños negocios, asfixiados por las restricciones impuestas por la pandemia.'),
(NULL,'Un año fumigando contra el coronavirus y otros casos de “teatro pandémico”','2021-02-24 09:43:53','La Administración estadounidense decidió fumigar las instalaciones de la Casa Blanca tras la marcha de Donald Trump. Así, horas antes de que Joe Biden ocupara la residencia presidencial, un equipo de operarios se dedicó a nebulizar desinfectante por las estancias. La semana pasada, los británicos veían cómo su primer ministro, Boris Johnson, se esmeraba con afán en la limpieza del asiento de una silla. Un año después de que un nuevo coronavirus sometiera al mundo, se toman demasiadas medidas de cara a la galería.'),
(NULL,'Maduro ordena la expulsión de la embajadora de la Unión Europea en Venezuela ','2021-02-24 20:23:20','El chavismo elevó este miércoles la tensión con Bruselas con un gesto que pretende demostrar el rechazo del Gobierno de Nicolás Maduro a toda acción internacional contra el régimen. Venezuela ordenó formalmente la expulsión de la embajadora de la Unión Europea, Isabel Brilhante, y le dio un plazo de 72 horas para abandonar su territorio.'),
(NULL,'24.000 profesores técnicos de FP subirán de categoría al integrarse en secundaria','2021-02-24 21:11:17','Unos 24.100 miembros del cuerpo de profesores técnicos de Formación Profesional se integrarán en el cuerpo de profesores de secundaria. El cambio, previsto en la nueva ley educativa, la Lomloe, supone un ascenso de categoría dentro del escalafón de los empleados públicos y, con ello, un aumento salarial. La integración es una reivindicación histórica de este colectivo docente. El principal requisito es tener un título universitario, con el que cuentan cerca del 85% de estos profesores. Los que no lo tienen, unos 4.250, continuarán con sus condiciones actuales hasta que se jubilen.'),
(NULL,'Primera señal de una estrella invisible que puede explicar el enigma de la materia oscura ','2021-02-24 19:25:36','Una señal de ondas gravitacionales generada hace más de 7.000 millones de años —la mayor que se ha captado hasta la fecha— se ha convertido en uno de los fenómenos más controvertidos y apasionantes de la física actual, pues con las leyes del universo en la mano no debería existir.'),
(NULL,'El fútbol español se prepara para dar la vuelta al mundo','2021-02-24 09:05:45','El primer recuerdo del fútbol español en América no es el más grato. 19 jugadores vascos, un entrenador británico –el famoso ‘Míster’ Harris– y un periodista zarparon el 27 de junio de 1922 desde Lisboa y cruzaron el Atlántico a bordo del Cap Polonio para arribar a Buenos Aires (Argentina) dos semanas más tarde, el 13 de julio. Fueron recibidos por gran parte de la sociedad vasca que había emigrado al Río de la Plata, y casi sin descansar, se midieron con una selección porteña.'),
(NULL,'Miley Cyrus, la nueva diva de los viejos rockeros','2021-02-24 16:33:27','La cantante culmina su transformación de edulcorado ídolo juvenil de Hannah Montana a celebrada rockera. Tras su éxito en el concierto previo a la Super Bowl, prepara un disco de versiones de Metallica.'),
(NULL,'Un periodista que viajó a Milán para cubrir el Valencia-Atalanta, positivo por coronavirus','2021-12-03 12:03:00','Se trata del segundo caso confirmado en la comunidad y el decimoquinto en España desde el lunes'),
(NULL,'Mapa de la expansión y claves para entender el coronavirus de Wuhan','2021-12-06 12:15:18','El nuevo coronavirus SARS-CoV-2, surgido en la ciudad china de Wuhan a finales de 2019, ha causado una de las mayores crisis sanitarias de los últimos años cuyas consecuencias, no solo sanitarias sino también económicas y sociales, son todavía impredecibles.'),
(NULL,'El turismo italiano se resiente; España mira expectante','2022-01-15 14:18:23','La patronal hotelera del área de Venecia describe un sector “al borde del colapso”'),
(NULL,'“La magnitud del problema del coronavirus no será diferente a una gripe”','2022-02-10 18:06:00','Ángel Gil de Miguel, catedrático de Medicina Preventiva y Salud Pública de la Universidad Rey Juan Carlos, lanza un mensaje de tranquilidad'),
(NULL,'El Gobierno salva el primer escollo de los Presupuestos gracias a ERC','2022-02-15 17:15:28','El voto en contra de Junts per Catalunya indigna a los republicanos'),
(NULL,'Sole Giménez, premio Manuel Margeliza 2022 de Estival Cuenca','2022-02-16 12:45:22','<img align="left" src="https://static4.abc.es/media/espana/2022/02/16/sole-kYE--620x349@abc.jpg">La cantante y compositora Soledad Giménez recibirá el premio Manuel Margeliza 2022 en la undécima edición de Estival Cuenca, que se desarrollará entre el 28 de junio y el 9 de julio de 2022, tal y como ha confirmado el director artístico, Marco Antonio de la Ossa. La cantante y compositora Sole Giménez, reconocida con el Premio Manuel Margeliza 2022 de Estival Cuenca, actuará el próximo 7 de julio en el escenario Solán de Cabras del Parador de Cuenca. La que fuera vocalista del grupo musical «Presuntos Implicados» durante veintitrés años y autora, en solitario, de nueve discos, será galardonada por su trayectoria y su compromiso con la visibilización a las mujeres compositoras. El premio, que se viene entregando desde el año 2014.'),
(NULL,'Cerca de 10.000 profesionales de Enfermería dispensar de medicamentos con receta electrónica','2022-02-16 12:31:54','<img align="left" src="https://static4.abc.es/media/espana/2022/02/16/receta-ks5E--620x349@abc.jpeg">El Gobierno de Castilla-La Mancha ha implementado la receta electrónica que ya permite a los profesionales de Enfermería la indicación, uso y autorización de dispensación de medicamentos y productos sanitarios de uso humano. Las más de 9.800 enfermeras y enfermeros que han sido acreditados hasta este momento ya pueden hacerlo a través del módulo de prescripción incluido dentro de "Turriano", el sistema de información corporativo para el área de Atención Primaria del Servicio de Salud de Castilla-La Mancha.'),
(NULL,'Las frases más duras contra Vox del discurso de Pablo Casado','2022-02-15 21:31:22','Pablo Casado ha pronunciado este martes un discurso que se suponía que era el análisis del partido sobre el resultado electoral en Castilla y León, pero finalmente se ha convertido en una nueva andanada contra Vox, al que ha criticado con una dureza que no se veía desde la moción de censura contra Sánchez si bien en esta ocasión al menos el popular no ha recurrido al insulto personal.'),
(NULL,'Barbón ocultó un informe que desmonta que la oficialidad del bable vaya a ser voluntaria para los asturianos','2022-02-16 08:42:00','PP, Cs y Vox han presentado distintas iniciativas para pedir explicaciones por el informe que el presidente del Ejecutivo autonómico mantuvo oculto sobre la oficialidad del asturiano. Mientras Vox insta al PP a presentar una moción de censura contra Adrián Barbón, Cs pide al presidente asturiano que se someta a una cuestión de confianza.'),
(NULL,'Feijóo exige en Génova que "por favor" se deje a Mañueco negociar su gobierno "sin tutelas"','2022-02-16 13:06:20','El líder gallego pide a la dirección nacional del PP que el candidato "popular" a presidir Castilla y León tenga manos libres para gestionar la investidura&nbsp;<a href="https://www.elmundo.es/elecciones/elecciones-castilla-y-leon/2022/02/15/620bed0521efa0af788b4570.html">Leer</a><img src="http://secure-uk.imrworldwide.com/cgi-bin/m?cid=es-widgetueditorial&amp;cg=rss-elmundo&amp;ci=es-widgetueditorial&amp;si=http://www.elmundo.es/rss/espana.xml" alt=""/>'),
(NULL,'Sectores del PSOE hacen frente al no es no de Pedro Sánchez en Castilla y León','2022-02-16 01:02:43','Socialistas sugieren esperar al primer paso de Mañueco para posicionarse en la formación del gobierno autonómico&nbsp;<a href="https://www.elmundo.es/elecciones/elecciones-castilla-y-leon/2022/02/16/620bed9121efa08c538b45a8.html">Leer</a><img src="http://secure-uk.imrworldwide.com/cgi-bin/m?cid=es-widgetueditorial&amp;cg=rss-elmundo&amp;ci=es-widgetueditorial&amp;si=http://www.elmundo.es/rss/espana.xml" alt=""/>');